version: '2'
services:
  nginx:
    container_name: poweredge-lb
    image: 'nginx'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - '80:80'
    restart: 'on-failure'

networks: 
  default: 
    external: 
      name: poweredge

